### ISSUE TITLE
Top scrubber disappears

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#1437] opened 2016-12-05 21:55 UTC
Steps to recreate:

1. Navigate to https://mallorn.dlib.indiana.edu/media_objects/avalon:3136
2. Start playing the item
3. Click on the magnifying glass to show the second scrubber
4. Click anywhere on the second scrubber to move the player head forward
5. Click on another track in the structural metadata to move the players
6. Click on the top scrubber to move the player head forward and move the mouse away from the scrubber.

In at most one second the top scrubber will disappear. Hovering the mouse over the area will bring it back and moving the mouse away again will enable it to disappear again.

**Comment by joncameron** [comment] 2016-12-05 22:05
@mcwhitaker This is standard behavior—the media player controls always disappear when the cursor is moved away or stopped on the player so the entire video can be displayed for playback when navigation controls aren't needed (and because they lay over the image itself). I think rather than a bug we could rewrite as an enhancement to decide on the behavior of the track scrubber... whether it should also disappear or how it should behave.

**Comment by mcwhitaker** [comment] 2016-12-05 22:14
Should the top scrubber always disappear, then? It only disappears if you click on the lower scrubber then later on the top scrubber. We probably should not have to hit a mysterious sequence of steps to prompt a certain behavior.

**Comment by joncameron** [comment] 2016-12-06 14:14
@mcwhitaker  It should, and it has that behavior for me (and that should be the intended behavior)—Firefox 50.0.2, macOS 10.11. However it doesn't work that way 100% of the time—I think there needs to be some sort of extra mouseover or click to get it to trigger. My guess is that the bug in this case is that the mediaelement control bar disappearing happens in some cases but not others, and that behavior needs to be refined. Track scrubber visibility is something I'd like to put in #1436 for the moment.

**Comment by mcwhitaker** [comment] 2016-12-06 14:56
@joncameron -- it does not matter to me on which ticket you put the work, so feel free to close this if you wish.

**Comment by joncameron** [comment] 2016-12-15 14:25
I will close this issue and write a new one focused on what the default behavior should be.

**Comment by davidschober** [comment] 2017-01-06 17:11
@joncameron closing per your comment (just doing Friday cleanup)

**Closed by davidschober** 2017-01-06 17:11 UTC
Labels: 5.x, bug
