### ISSUE TITLE
Implement Timeliner with Video in Avalon

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4906] opened 2022-10-07 13:46 UTC
# Description
Timeliner has been updated to include support for video display of media resources. This change should be evaluated and pulled into Avalon so users can create Timelines from video content.

# Done Criteria
- [x] New Timeliner version updated within Avalon
- [x] Explicitly set video for video media in the manifest generated by Avalon for new timelines (currently everything is designated as audio regardless of resource type)

**Comment by elynema** [comment] 2022-12-02 17:28
This looks like it is working in avalon-dev and avalon-staging for new timelines. @Dananji It looks like video is not added to pre-existing timelines. Is that as expected? Also, it looks like the video player in Timeliner doesn't include captions. Is that as intended?

**Comment by Dananji** [comment] 2022-12-02 17:40
Yes, both are expected.
Preexisting timelines doesn't have video, because we added video to the manifests in Avalon's manifest generation code to identify video items when the Timeliner build with video was added.
We didn't work on displaying captions in the video player as a part of the initial work, but this could be future work if there's a need for it.

**Comment by elynema** [comment] 2022-12-02 19:39
@joncameron This looks good, except for the bit about explicitly setting video in the timeline manifest, which I have not been able to figure out how to test. I can't see how to get a manifest for a timeline in Avalon.

**Comment by cjcolvar** [comment] 2022-12-02 21:00
@elynema I don't think we link to it anywhere in the interface.  You can construct the url for it by adding `/manifest.json` to the timeline url. (e.g. https://media.dlib.indiana.edu/timelines/1/manifest.json)

**Comment by elynema** [comment] 2022-12-02 22:18
It *looks* like it is labeling the media content with type Video in the manifest, but I'd pefer Jon to give the final thumbs up on this one.

**Comment by joncameron** [comment] 2022-12-06 13:46
I'm running into an issue on dev where the Timeliner can't grab the m3u8 and locks up.

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://avalon-dev-hls.dlib.indiana.edu/avalon/3a22aa7a-3f27-4afb-96cd-ab42d33261ff/outputs/lunchroom_manners-high.mp4/index.m3u8. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 403.

![Screen Shot 2022-12-06 at 8.47.19 AM.png](https://images.zenhubusercontent.com/5cc1c0106d0be2229caf2d9e/f8546572-a582-46b1-b7fc-9cbc4634d330)

**Comment by joncameron** [comment] 2022-12-06 14:04
I did confirm that the "video" value for type came through.

**Comment by elynema** [comment] 2022-12-07 17:56
Note that the issue Jon saw had to do with a CDL item that was not checked out to the user and has been moved to #5000. Closing this.

**Closed by elynema** 2022-12-07 17:56 UTC
Labels: timelines
