### ISSUE TITLE
Special Access To Single User Prevents Visibility in LTI Context

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#2315] opened 2017-09-13 14:16 UTC
### Description
From Brian: "that one item (The Silence) that wouldn't show up in the Z284 LTI course: All the access control settings for 'The Silence' looked the same as the other 11 items in that course (which were showing up) except that The Silence had special access granted for user djbishop. I removed that special access and now the item shows up as expected. Something about our application of access rules seems to be broken."

**Comment by bkeese** [comment] 2017-09-13 14:21
Duplicate of https://github.com/avalonmediasystem/avalon/issues/2316

**Closed by bkeese** 2017-09-13 14:21 UTC
Labels: 6.2, bug, Needs Refinement
