### ISSUE TITLE
Markers not working in Safari

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2578] opened 2017-12-15 16:28 UTC
_From @davidschober on December 15, 2017 16:17_

To Recreate:

- Go to a playlist <https://spruce.dlib.indiana.edu/playlists/100> using safari
- click on a marker
- see that the playhead is not moved forward to proper position

_Copied from original issue: avalonmediasystem/avalon-planning#221_

**Comment by cjcolvar** [comment] 2017-12-15 20:22
Might be fixed by #2586

**Comment by cjcolvar** [comment] 2017-12-16 03:03
I wasn't able to reproduce with the latest on spruce.

**Comment by joncameron** [comment] 2017-12-19 15:57
Couldn't reproduce this, but I filed another Safari marker bug: #2620

**Closed by joncameron** 2017-12-19 15:57 UTC
Labels: 6.3, bug, In Review, quality assurance
