### ISSUE TITLE
ensure embed size of me4js player is the same as me2

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2510] opened 2017-12-06 18:33 UTC
## Description

Currently the embedded me4js player is not the same size as it's ME2 counterpart. Ensure that it's the same size.  

audio:

width: 600
Height 50

Width: 600
Height: 337

**Comment by davidschober** [comment] 2017-12-06 18:42
@cjcolvar this looks to be the same size in the embed code
![screen shot 2017-12-06 at 12 41 41 pm](https://user-images.githubusercontent.com/4803230/33678931-e96310b6-da82-11e7-95ad-fabf65b77add.png)

Can this be closed?

**Comment by davidschober** [comment] 2017-12-06 18:43
masters issue #2504

**Comment by phuongdh** [comment] 2017-12-06 19:29
@davidschober the issue is that the embed iframe dimensions are and have always been generated from the the actual video dimensions, but the mejs4 player aspect ratio is now fixed (at about 1.45), so sometimes the player is smaller or bigger than the iframe viewport. Case in point:

![image](https://user-images.githubusercontent.com/1304657/33681180-cc363518-da91-11e7-83af-6a81d44f4de7.png)

**Comment by davidschober** [comment] 2017-12-07 15:16
Sounds good. @phuongdh we can move with it.

**Comment by joncameron** [comment] 2017-12-20 14:50
This needs some more work—see the image below.
<img width="628" alt="screen shot 2017-12-20 at 9 48 22 am" src="https://user-images.githubusercontent.com/1406618/34212698-1eb67a58-e56b-11e7-8691-ba7d8a33cebc.png">
The elements are higher up in the mejs4 version, which throws things off balance and obscures the timecode popup when a user does a mouseover on the rail.

**Comment by bkeese** [comment] 2017-12-20 18:08
Is that also a full-screen button for audio on spruce?

**Closed** 2017-12-20 21:37 UTC
Labels: 1 | MediaElement Upgrade, 6.3, In Review, quality assurance
