### ISSUE TITLE
long-lasting flash message

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#2042] opened 2017-06-08 19:49 UTC
## Description
When you add a marker to a playlist item, you get the success message:

![image](https://user-images.githubusercontent.com/16720883/26947689-968bbb7c-4c61-11e7-9ed3-41dad38d67bb.png)

The problem is that the message does not disappear and does not have the usual "x" that gives the user the ability to dismiss it. 

### Done looks like
User is given the option to get rid of that message.

### Tasks
- [ ]  Add the 'X' markup to the flash message

**Comment by joncameron** [comment] 2017-12-14 14:45
@bkeese Can the button to remove the flash message also be added to the add_marker_to_playlist_item_alert div on the playlist view page? The PR attached adds the button to remove the flash message when adding a playlist item, but not when adding a marker to a playlist.

**Comment by bkeese** [comment] 2017-12-14 14:48
A fix for this is in a PR that is waiting to be merged.

**Comment by Karthikeya212** [comment] 2017-12-15 17:05
Tested on Spruce. The 'x' mark is appearing on the messages to allow the user close it, but if it closed once then the next messages were not generating. 
1. Start playing an item and add it to a playlist
2. It generates a message saying that it is successful, do not act (close) on it.
3. Add it again to the playlist. It again generates the messages. Now close this message using 'x'.
4. Again add it to the playlist, from now on it doesn't generate the message.
Can check the same behavior after adding markers as well, once a message is closed it doesn't display any of the further messages.

**Comment by cjcolvar** [comment] 2017-12-15 20:21
I'm pulling this back to Current Sprint since I could reproduce @Karthikeya212's steps.

**Comment by Karthikeya212** [comment] 2017-12-19 16:45
Tested on Spruce and is working fine

**Closed by Karthikeya212** 2017-12-19 16:45 UTC
Labels: 6.3, bug, In Review, quality assurance, tasked, ux
