### ISSUE TITLE
Batch ingest picking up wrong files intermittently

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2055] opened 2017-06-12 18:26 UTC
Server: mallorn.dlib.indiana.edu
Testing: Performance
Browser: Chrome(58.0.3029.110 (64-bit))
Flash version: 24.0.0.221
Operating System: Windows10
Issue: Some times batch ingest is picking-up wrong files to ingest. It is just picking up wrong file names but as it couldn't find the actual master files the conversion process is paused forever and is not completing.

### Steps to reproduce the behavior
1. Login to mallorn.
2. Batch ingest a 100 section item

On the occurrence of that issue:

We can see some sections which don't ingest any further
![wrong file](https://user-images.githubusercontent.com/25850972/27048596-7b6e2c0a-4f7a-11e7-812f-be36cfb32ba7.PNG)

All the remaining section ingests will be completed but the conversion bar will remain unfinished and don't even show the conversion failure(red color)
![wrong file conversion bar](https://user-images.githubusercontent.com/25850972/27048642-a00316b6-4f7a-11e7-8dca-4b1ba4d5f903.PNG)

The mail read that those sections were cancelled
![wrong file mail](https://user-images.githubusercontent.com/25850972/27048663-b21db40a-4f7a-11e7-8e63-8e24dd8357cc.PNG)

### Related work

These are some of the items in Mallorn which got this issue:
https://mallorn.dlib.indiana.edu/media_objects/q237hr95t
https://mallorn.dlib.indiana.edu/media_objects/8g84mm259
https://mallorn.dlib.indiana.edu/media_objects/ht24wj41z

### Related Issues
Failure to create ActiveEncode job returns unrelated job's metadata: #2060

**Comment by cjcolvar** [comment] 2017-06-12 18:29
From some investigation on mallorn it looks like the master files have the correct file but the Matterhorn workflow it is associated with has the incorrect file.  I'm guessing that the workflow wasn't created with the wrong file but rather that the wrong workflow id was returned to the master file at some point.

**Comment by bkeese** [comment] 2017-06-12 20:59
We've identified the cause of the corrupted data: 
ActiveEncode::Base.find(nil) doesn't throw an error or return nil, it returns an unrelated encode instance.
https://github.com/avalonmediasystem/avalon/blob/master/app/models/master_file.rb#L249

**Comment by cjcolvar** [comment] 2017-06-13 14:34
@avalonmediasyste/product-owners I'm going to create a separate issue for this ActiveEncode issue which I think is high priority.  When that is fixed, I think this could be downgraded to normal priority.  This bug would become figure out why under heavy load active_encode/matterhorn create is failing sometimes.

**Comment by cjcolvar** [comment] 2017-07-05 13:44
I think the work for fixing this is all happening in #2060.  Could we close this as duplicate or just close it the same time?

**Comment by davidschober** [comment] 2017-07-13 14:18
This is closing as a dupe

**Closed by davidschober** 2017-07-13 14:18 UTC
Labels: backlog buddies, bug, duplicate, Needs Refinement
