### ISSUE TITLE
Use original mediainfo gem instead of avalon fork

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#4194] opened 2020-06-17 15:44 UTC
Mediainfo gem has been seeing [frequent updates](https://rubygems.org/gems/mediainfo/versions/)

Their updates include `Other` stream fix (the reason we forked), S3 presigned url (what I am trying to fix with mediainfo v20.03) and it's a good idea to get off of our 2013 fork anyway. However a lot has been changed since 2013 so we need to test thoroughly and expect quite some code changes.

**Comment by phuongdh** [comment] 2020-06-17 19:19
This didn't fix our presigned url problem.

**Comment by joncameron** [comment] 2020-09-17 14:24
We'll pass on this story until we can move to upstream MediaElement.

**Comment by joncameron** [comment] 2023-04-18 19:57
Duplicate of #5059

**Closed by joncameron** 2023-04-18 19:57 UTC
