### ISSUE TITLE
Select Playlist Drop-Down in Media Player Doesn't Activate

### ISSUE THREAD

**Issue by mschnaars** [avalonmediasystem/avalon#3044] opened 2018-08-22 17:11 UTC
### Description

After selecting the Add to Playlist icon in the Media Player, the Playlist drop-down does not activate; only the default playlist is usable. Any of the other Add to Playlist options (below the media player in the item structure) work as expected.

### Environment
Spruce, Avalon 6.4.3, Chrome and Edge

### Screenshots
![playlistdropdown_error](https://user-images.githubusercontent.com/25825877/44478857-e95ffb00-a60c-11e8-8304-a1eb80adbf5e.png)

**Comment by davidschober** [comment] 2019-01-03 15:12
Need to verify first.

**Comment by cjcolvar** [comment] 2019-01-07 16:55
I'm able to reproduce this issue on spruce.  The full list of playlists is rendered in the DOM so the issue is in some of the markup that wires up the select2 or it is a JS issue.

**Comment by cjcolvar** [comment] 2019-01-16 20:50
This issue is fixed with #3143 but it exposed a new issue on spruce.  I'm closing this one and will open a new one.

**Closed by cjcolvar** 2019-01-16 20:50 UTC
Labels: In Review, bug 🐛
