### ISSUE TITLE
Extra playlist item highlighting arrow inserted for the first item in a playlist

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2799] opened 2018-02-02 14:39 UTC
Server: spruce.dlib.indiana.edu
Browser: Chrome63 (Windows10)
Issue: Usually when playing a playlist, user can see an arrow to the left of the current playing item. This is still there but there is an additional arrow that inserted for the first item in every playlist that never disappears even after that item is finished playing.
![image](https://user-images.githubusercontent.com/25850972/35738372-b58b57e2-07fc-11e8-9a7b-cb49f9a38bab.png)

**Comment by Karthikeya212** [comment] 2018-02-02 14:40
This is the case in mco-staging.
![image](https://user-images.githubusercontent.com/25850972/35738535-246331c6-07fd-11e8-8a86-15a827e765f4.png)

**Comment by imacubsfan23** [comment] 2018-06-22 19:18
I can't reproduce this issue on the website to see this problem.
It seems to me (because I'm new to the avalon media system repo) that the ui doesn't look like the above issue any more. 
Is there some way I can reproduce this issue now?

**Comment by mcwhitaker** [comment] 2018-06-25 18:48
@imacubsfan23 Thank you for bringing this up. The ticket is old, so it looks like our current version does not have this bug. I will close the issue.

**Closed by mcwhitaker** 2018-06-25 18:48 UTC
Labels: bug
