### ISSUE TITLE
Items don't show up in collection landing page on Spruce

### ISSUE THREAD

**Issue by Dananji** [avalonmediasystem/avalon#4507] opened 2021-07-29 14:48 UTC
### Description

When clicked on the collection name on the details panel of an item on the item page, the collection landing page is shown. But it doesn't show the item and shows the following message:
![Screenshot from 2021-07-29 10-46-32.png](https://images.zenhubusercontent.com/5cc1c66b3244e00362de97ea/b94a1c53-76cc-433c-b1e7-776a10cb39e0)

This was experienced on Spruce (logged in as an admin user).

To reproduce:

1. Click on 'Browse' and click on an item
2. On the item page, click collection title from the 'Details' panel

### Done Looks Like

Collection landing page shows the items, that the logged in user can access.

#### Notes
When the item is unpublished/published (based on its current status) it shows up in the collection landing page.

**Comment by joncameron** [comment] 2021-07-30 13:24
I couldn't reproduce this (https://spruce.dlib.indiana.edu/collections/9880vq965 displays the item within) except for the "7.1 Testing Collection". My guess is that this is another character issue in the query that populates the list for the collection. This was encountered earlier with a '&' character in collection names, https://github.com/avalonmediasystem/avalon/issues/4084.

**Comment by Dananji** [comment] 2021-07-30 14:28
I still see this with some items.
For an example, try this item: https://spruce.dlib.indiana.edu/media_objects/cf95jb62q.
When clicked on collection name in the `Details` panel the collection landing page for `Fancy Dog` doesn't show the item. And also the collection `Fancy Dog` is not listed in the collection facet in the `Browse` page.
My guess is, this might be related to solr index.

**Comment by joncameron** [comment] 2021-08-05 14:18
Publish and unpublish actions are affecting the index in an unusual way. Publish/unpublish and indexing effects should be looked into.

**Comment by cjcolvar** [comment] 2021-09-01 15:11
Probably bad data.  Can't reproduce with that item after publishing/unpublishing.  Closing.

**Closed by cjcolvar** 2021-09-01 15:11 UTC
Labels: bug 🐛
