### ISSUE TITLE
Bug in Access Control panel

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#4270] opened 2020-09-11 18:48 UTC
### Description
When removing multiple entries from MediaObject edit, Special Access panel, I encountered this error:
```
A copy of AccessControlStep has been removed from the module tree but is still active!
app/models/access_control_step.rb:114:in `execute'
```

This needs to be reproduced; was experienced in Phuong's development environment and he could not reproduce in Spruce.

### Done Looks Like
- Testing done to see if this can be reproduced in Spruce
- Issue is updated as needed

**Comment by Dananji** [comment] 2021-01-27 18:51
I was not able to reproduce this on Spruce (Avalon 7.2.0)

**Comment by joncameron** [comment] 2022-06-22 18:21
Not reproduced; closing.

**Closed by joncameron** 2022-06-22 18:21 UTC
Labels: bug 🐛, qa  🔍
