### ISSUE TITLE
Determine wave tooling

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#3023] opened 2018-08-03 15:05 UTC
## Description

Work with Peak.js and Wavesurfer to see what kind of interactions are available (handles, etc). Ensure that we can get time signatures to power the structural metadata editor

## Done looks like

- we work with Peak and maybe wavesurfer
- document interactions as necessary.

**Comment by cjcolvar** [comment] 2018-08-10 15:53
@davidschober This feels like a duplicate of #3020 which we decided to close yesterday in favor of just running with peaks.js for now.  So can we close this issue?

**Comment by joncameron** [comment] 2018-08-17 14:39
I'm going to close since I agree with Chris that it's a dupe of #3020. Our current plan is to dive in with Peaks.js.

**Closed by joncameron** 2018-08-17 14:39 UTC
Labels: duplicate, ready
