### ISSUE TITLE
Appending a string null to the title of the playlist item if it added using Add to Playlist icon present in section panels

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2740] opened 2018-01-11 19:11 UTC
### Description
An additional string 'null' is appended to the playlist item title if the item is added to the playlist using "Add to playlist" icon present in the section panels. however the title is fine if the item is added using the "Add to playlist" icon present in player.

![image](https://user-images.githubusercontent.com/25850972/34842368-468c079e-f6d9-11e7-8ab7-be2457330346.png)

**Comment by cjcolvar** [comment] 2018-01-11 19:14
Just to clarify, this is the playlist item's description that is being initialized with 'null' instead of an empty string.

**Comment by cjcolvar** [comment] 2019-05-23 16:54
Duplicate of #2689 .

**Closed by cjcolvar** 2019-05-23 16:54 UTC
Labels: bug 🐛
