### ISSUE TITLE
[iOS Specific]:- Videos are not playing properly and getting stuck.

### ISSUE THREAD

**Issue by anirudhpillai16** [avalonmediasystem/avalon#937] opened 2016-06-28 17:45 UTC
Steps to Reproduce 

1. Launch Lancelot or Mallorn on iOS Device.e.g:- iPhone 6S or 6S Plus.
2. Access any video from Moving Image.
3. Play video

Observe video fails to play properly and gets stuck on same frame

Note:- If user double taps on video screen, video plays correctly in full screen.

**Comment by cjcolvar** [comment] 2016-07-05 14:53
Browserstack is being flaky and we can't reproduce it on physical devices.

**Comment by davidschober** [comment] 2016-07-05 15:06
@csyversen we have some physical devises here. I'll get some folks to check.

**Comment by davidschober** [comment] 2016-07-05 15:14
@csyversen we can't reproduce it. Closing.

**Closed by davidschober** 2016-07-05 15:14 UTC
Labels: bug, In Review
