### ISSUE TITLE
Seek in Media Player By Interacting With Structure

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#1840] opened 2017-04-21 20:29 UTC
### Description
IIF-AV player should be able to navigate the video by interacting with the structure

### Done Looks Like
TBD

**Comment by davidschober** [comment] 2017-04-26 20:00
@joncameron is this a dupe of #1844?

**Comment by davidschober** [comment] 2017-05-03 15:55
Jon, closing as dup. Please reopen if necessary.

**Closed** 2017-05-03 15:55 UTC
Labels: iiif-av
