### ISSUE TITLE
IPAD Playthrough on item page advances correctly but does not start playback

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#2610] opened 2017-12-18 22:40 UTC
## Description

On iOS 10, 11 when playing through a multi-section  media object, the player will advance to the next item but not start the item.

To recreate:

- using an iPad, go to: https://spruce.dlib.indiana.edu/media_objects/4q77fr355
- let it play through to the end
- see that it does not start the Caruso track 

## Punchlist
#2609

**Comment by cjcolvar** [comment] 2017-12-19 18:49
I'm thinking this is the same as this: https://github.com/avalonmediasystem/avalon/issues/2611#issuecomment-352850007

**Comment by joncameron** [comment] 2017-12-20 15:30
Closing as a dupe of #2611.

**Closed by joncameron** 2017-12-20 15:30 UTC
Labels: duplicate, ready
