### ISSUE TITLE
We are not escaping special characters in solr upon solrization

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#2147] opened 2017-07-07 20:00 UTC
### Update:

Whenever any field has one of solr's special characters:

`+ - && || ! ( ) { } [ ] ^ " ~ * ? : \` we need to escape it with another `\`

This would be on all the controllers we call to_solr on and other places we solrize.  It may be only certain fields are not escaping right now since it doesn't seem to happen in all of them.

### Description
For example in the terms of use, insert:
`The audio recordings on this web site are from material in the collections of the Melville J. Herskovits Library of African Studies of Northwestern University Libraries, are provided for use by its students, faculty and staff, and by other researchers visiting this site, for research consultation and scholarly purposes only. Further distribution and/or any commercial use of the audio recordings from this site is not permitted. Please contact africana@northwestern.edu with questions. COPYRIGHT UNDETERMINED`

Leads to weird escaping.  This is not a display issue, when you go into `MediaObject.descMetadata.terms_of_use` it has been stored with the array brackets.  It still solrizes as a string though.  You can stick the `/` in via console without any issue, so appears to be somewhere down in the batch processing.

<img width="465" alt="screen shot 2017-07-07 at 3 57 42 pm" src="https://user-images.githubusercontent.com/5350060/27974756-4b0ee1dc-632d-11e7-8c26-c6d11c6710a8.png">

**Comment by carrickr** [comment] 2017-07-07 20:30
Per @jlhardes testing on Spruce, only seems to happen with terms of use, does not occur with summary

**Comment by davidschober** [comment] 2017-07-20 14:42
CHRIS: is it anything in the field or is it special characters?

**Comment by davidschober** [comment] 2017-07-20 14:43
Note, complete this with #2145

**Comment by davidschober** [comment] 2017-08-16 20:33
@carrickr is this is play with #2145 (batch updates?) if so let's move this to ibn progress.

**Comment by davidschober** [comment] 2017-09-27 20:44
Note completed with other w

**Comment by carrickr** [comment] 2017-09-28 19:18
Batch won't fix this, since this is happening up in solrization.

Whenever any field has one of solr's special characters:

`+ - && || ! ( ) { } [ ] ^ " ~ * ? : \` we need to escape it with another `\` in the to_solr call.

**Comment by cjcolvar** [comment] 2017-09-29 14:50
Solrization should be escaping all of these characters.  I think this is an issue between single vs. multiple values and not handling the fact that all fields appear as multiple by default.

**Comment by bkeese** [comment] 2017-10-04 18:37
I couldn't see this behavior in the UI, so it's not real clear to me where this problem is presenting itself. But it might just be a matter of how the field is requested: 
```
[13] pry(main)> m = MediaObject.find('9593tv123')
=> #<MediaObject id: "9593tv123", permalink: "", duration: "429347", avalon_resource_type: ["sound recording"], avalon_p
ublisher: nil, avalon_uploader: "archivist1@example.com", identifier: [], head: [#<ActiveTriples::Resource:0x5b8e91c(#<A
ctiveTriples::Resource:0x0000000b71d238>)>], tail: [#<ActiveTriples::Resource:0x5b91c84(#<ActiveTriples::Resource:0x0000
000b723908>)>], access_control_id: "a1ce395e-eb26-4190-b1c4-a4f7ee4b1496", governing_policy_ids: ["nk322d32h"], collecti
on_id: "nk322d32h">
[14] pry(main)> m.title
=> "Best of the 70s"
[15] pry(main)> m.descMetadata.main_title
=> ["Best of the 70s"]
[16] pry(main)> m.terms_of_use
=> "test two terms of use"
[17] pry(main)> m.descMetadata.terms_of_use
=> ["test two terms of use"]
```

**Comment by cjcolvar** [comment] 2017-10-12 15:04
@Karthikeya212 @joncameron @davidschober can we close this issue since @bkeese couldn't reproduce it?

**Comment by davidschober** [comment] 2017-10-12 18:58
If we can't reproduce it, let's close it.

**Closed by davidschober** 2017-10-12 18:58 UTC
Labels: 6.3, bug, in progress
