### ISSUE TITLE
Section label edit fails for non-admin users

### ISSUE THREAD

**Issue by mohideen** [avalonmediasystem/avalon#4522] opened 2021-08-23 20:37 UTC
A collection manager was trying to edit the section label of a published media object, but it did not work as intended. After updating the label, when the "save" button is clicked, the operation fails with "Failed to update." message. From looking into the code, it seems that the CanCan ability configuration for "ActiveFedora::Base :update" is being used instead of "MasterFile :edit" ability configuration. Explicitly adding the `:update` ability configuration for MasterFile seems to fix the issue.

References:
- https://github.com/samvera/hydra-head/blob/main/hydra-access-controls/lib/hydra/ability.rb#L45
- https://github.com/umd-lib/avalon/blob/avalon-develop/app/models/ability.rb#L131

![image](https://user-images.githubusercontent.com/1703851/130516045-e577c71e-bd64-4534-b48c-8e6b5baf5a61.png)

**Comment by joncameron** [comment] 2021-09-02 14:27
@srongala Can you please try to reproduce this in our test environment?

**Comment by cjcolvar** [comment] 2021-09-07 14:46
@mohideen Thanks for submitting this issue and PR!
It looks like this change has already been merged into the develop branch but hasn't made it into a release yet (#4379).  I'm going to close this PR and the related issue as already fixed.  Hopefully the fix will make it into a release soon but we don't have one scheduled yet.

**Closed by cjcolvar** 2021-09-07 14:46 UTC
