### ISSUE TITLE
MEJS4: lil' scrub behavior in fullscreen mode

### ISSUE THREAD

**Issue by phuongdh** [avalonmediasystem/avalon#2531] opened 2017-12-12 16:08 UTC
1. Enabling lil scrub takes the player out of fullscreen. Is this intentional?

2. Disabling lil scrub also takes the player out of fullscreen. This is quite jarring. 

Would be best if lil scrub is visible and working, or the button is hidden in fullscreen mode,

**Comment by bkeese** [comment] 2017-12-12 16:12
Related to this issue where it was decided to leave full screen if a button is pressed that can be handled in fullscreen mode: https://github.com/avalonmediasystem/avalon/issues/2024

**Comment by cjcolvar** [comment] 2017-12-12 17:50
If we don't support lil scrub in fullscreen, I'd vote for hiding it in that context.

**Comment by davidschober** [comment] 2018-01-24 21:11
@joncameron and I called this OK for now. We're going to "won't fix".

**Closed by davidschober** 2018-01-24 21:11 UTC
Labels: bug, wontfix

**Comment by cjcolvar** [comment] 2019-05-23 17:22
@joncameron @davidschober Can we remove this from the Known Issues since it is the expected behavior now?
