### ISSUE TITLE
CSS issue with bulk operations pop-up window

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2392] opened 2017-10-16 15:58 UTC
### Descriptive summary
Server: spruce.dlib.indiana.edu
Testing: Regression 
Browser: Chrome(61.0.3163.100 (64-bit))
Operating System: Windows10
Issue: CSS issue with bulk operations pop-up window

### Steps to reproduce
1. Select some objects and navigate to Manage Selected Objects page.
2. Try to do any bulk operation that opens a pop-up window such as Move/Delete/Add to playlist etc.
3. The pop-up window includes the header and footer of avalon.
![image](https://user-images.githubusercontent.com/25850972/31622016-38f4d89a-b269-11e7-874c-f467e8fa1df1.png)

**Comment by cjcolvar** [comment] 2017-10-16 16:41
AWS merge cleanup?

**Comment by cjcolvar** [comment] 2017-10-16 20:01
This is due to pulling in the latest version of blacklight 6.11.2 which introduced this regression.  There is a PR into blacklight which fixes this: https://github.com/projectblacklight/blacklight/pull/1797
I'm going pin to Blacklight 6.11.0 until this gets merged and released.

**Closed** 2017-10-16 20:49 UTC
Labels: bug
