### ISSUE TITLE
No User Feedback When Using Remove Button for Captions on Masterfile 

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#4446] opened 2021-04-28 19:36 UTC
### Description
Clicking the "Remove" button appears to clear the subtitle file, but only after a refresh of the page. There's no feedback to the user that the caption has been removed, and the filename is still populated to the left of the button.

### Done Looks Like
- Notification message to user appears letting them know the caption has been removed
- Caption filename in UI disappears when the caption is removed

**Comment by Dananji** [comment] 2021-11-01 17:47
Cannot reproduce this on spruce, hence closing.

**Closed by Dananji** 2021-11-01 17:47 UTC
Labels: bug 🐛
