### ISSUE TITLE
[BUG] Scrubber resets in the media player when a user tries to skip ahead in the progress bar

### ISSUE THREAD

**Issue by charumitraravi** [avalonmediasystem/avalon#5388] opened 2023-09-27 13:52 UTC
**Describe the bug**
When a user tries to skip ahead through time in the progress bar in the media player by clicking on a particular time in the progress bar, The scrubber resets to the beginning and the video starts to play from the start. 

**To Reproduce**
1. Open an item containing multiple audio/ video section files. 
2. Let the player play the first section fully and move on to the second section.
3. Once the second section starts playing, try to skip ahead in the progress bar by clicking on a random point point in the progress bar ahead of the current time.

**Expected behavior**
The scrubber should skip to the point where the player clicks and the video/audio should start playing from that point

**Screenshots/Screen Recording**
https://samvera.slack.com/files/U04P1T8U0UD/F05UCSXGT89/screen_recording_2023-09-26_at_12.30.30_pm.mov

**Environment (please complete the following information):**
 - Device / platform [e.g. laptop, iphone pro 12]: All devices
 - OS: Any OS
 - Browser [e.g. chrome version 90.0.4430.93] : All major browsers 
- [x] avalon-dev
- [ ] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo

**Release:**
v7.7

**Additional notes**
Any additional information or notes that may be helpful in diagnosing or fixing the problem.

**Comment by elynema** [comment] 2023-10-04 19:51
Seems to be working on avalon-dev now, but auto-advance is not working there now. Need to re-test after auto-advance is re-enabled on avalon-dev.

**Comment by Dananji** [comment] 2023-10-17 17:17
Tested this in avalon-dev for the item in the demo attached in the ticket, and couple of other multi-sectioned items, and was not able reproduce the bug.
Seems to be fixed with the latest Ramp build.

**Closed** 2023-10-17 17:41 UTC
Labels: bug 🐛
