### ISSUE TITLE
On a Vanilla Install, Developers Get Migration Error

### ISSUE THREAD

**Issue by carrickr** [avalonmediasystem/avalon#1871] opened 2017-05-03 20:11 UTC
```
StandardError: An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: table "annotations" already exists:

[3:42] 
Then it ends with:

[3:42] 
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
```

This is caused by `20170503194037_create_annotations_active_annotations_rb.rb` somehow being added in whenever rake db:migrate is called.  The date will be today's date (so 20170503 will change).

**Comment by carrickr** [comment] 2017-05-03 20:43
Correction, looks like somehow this migration is created:
[20170503194037_create_annotations_active_annotations_rb.txt](https://github.com/avalonmediasystem/avalon/files/974646/20170503194037_create_annotations_active_annotations_rb.txt)

We either need to have this not be created or alter `b/migrate/20160825153112_add_annotations_clips_markers.rb` to use change_table over create_table

**Comment by davidschober** [comment] 2017-05-10 16:02
@cjcolvar is this fixed with your current migration work?

**Comment by cjcolvar** [comment] 2017-05-10 18:00
I don't know if this is still a problem.  I'll test it out myself.

**Comment by cjcolvar** [comment] 2017-05-10 18:33
I wasn't able to reproduce this with a fresh checkout of master skimming through the instructions here https://wiki.dlib.indiana.edu/display/VarVideo/Getting+Started+(OS+X).

**Comment by joncameron** [comment] 2017-05-17 15:00
@cjcolvar I'm going to close this since you weren't able to reproduce.

**Closed** 2017-05-17 15:02 UTC
Labels: 6.x, bug, Needs Refinement
