### ISSUE TITLE
Upgrade node and webpack versions

### ISSUE THREAD

**Issue by cjcolvar** [avalonmediasystem/avalon#5292] opened 2023-08-07 18:57 UTC
# Description
Avalon currently builds with node 14, which is EOL, and webpack 4, which has an issue requiring a flag for a legacy SSL provider.  We should upgrade to the latest versions of each that work with our JS dependencies in Ramp, SME, Timeliner, etc.

# Done Looks Like
-

**Comment by joncameron** [comment] 2023-08-16 19:01
Dupe of #5304?

**Closed** 2023-08-16 19:06 UTC
