### ISSUE TITLE
IIIF-AV: Decide where code for manifest generation should live

### ISSUE THREAD

**Issue by bkeese** [avalonmediasystem/avalon#1818] opened 2017-04-12 14:43 UTC
Based on #1816, decide how to incorporate manifest-generating code

**Comment by davidschober** [comment] 2017-04-12 20:29
@bkeese I think this is a dupe of #1775 . 

Note:

Hyku's IIIF endpoint is here:
https://github.com/projecthydra-labs/hyku/blob/master/app/controllers/concerns/hyku/iiif_manifest.rb
which uses iiif-manifest to actually construct the manifest:
https://github.com/projecthydra-labs/iiif_manifest/
starting here in ManifestFactory:
https://github.com/projecthydra-labs/iiif_manifest/blob/master/lib/iiif_manifest/manifest_factory.rb

So I think we'll have to figure out how to augment those manifests. 

@bkeese if this is a dupe, can you close?

**Closed** 2017-04-12 20:35 UTC
Labels: duplicate, ready
