### ISSUE TITLE
Cannot add markers for the playlist items

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2322] opened 2017-09-15 14:58 UTC
### Descriptive summary

Server: mallorn.dlib.indiana.edu
Testing: Regression
Browsers: Chrome
Operating System: Windows10
Issue: Cannot add markers for the playlist items

### Steps to reproduce the behavior

1. Add items to any playlist.
2. Go to the playlist and play an item.
3. Try to add marker for that item.
4. It is returning and error message stating that the user is unauthorised.
5. The page reloads but you can see that the items are still present in first playlist and the second playlist is still empty.
![image](https://user-images.githubusercontent.com/25850972/30489271-d088f358-9a04-11e7-961d-842fc453ff25.png)

**Comment by cjcolvar** [comment] 2017-09-15 16:10
It looks like the add marker form doesn't include the playlist_item_id so it fails for everyone always.  I'm working on a fix for this.

**Comment by cjcolvar** [comment] 2017-09-15 17:50
FWIW I couldn't reproduce this on IU production which is a pre-6.2 Avalon.

**Comment by cjcolvar** [comment] 2017-09-18 12:56
Fix is deployed to spruce.

**Closed** 2017-09-20 14:31 UTC
Labels: 6.2, bug, In Review, quality assurance
