### ISSUE TITLE
Structural metadata not updating properly

### ISSUE THREAD

**Issue by Dananji** [avalonmediasystem/avalon#5086] opened 2023-03-01 18:08 UTC
### Description

Structural metadata updated via either SME or XML editor is not being reflected in both SME and item page. Changes are only visible in XML editor.

To reproduce:
1. Go to the structure edit page for a media object
2. Edit and save structural metadata for a section using SME
3. Refresh page and open XML editor > Shows the changed structural metadata
4. Open SME > Shows the previous structural metadata (without the new changes)
5. Go to the item page > Shows the previous structural metadata

SME uses the structure information in the IIIF manifest, which is not getting updated properly.

### Done Looks Like
- [ ] Structural metadata is consistent throughout all pages - SME, XML editor, item page

**Comment by joncameron** [comment] 2023-03-01 20:07
Will need more testing since it's an intermittently occurring issue. 
Does the XML pull from a different endpoint, that it is the only one in which change are visible?

**Comment by elynema** [comment] 2023-03-09 15:32
I am also seeing network errors when trying to edit structure saving it and closing it several times. Here are some example records where this is happening:

https://avalon-dev.dlib.indiana.edu/media_objects/000000000/edit?step=structure
https://avalon-dev.dlib.indiana.edu/media_objects/0g354f213/edit?step=structure

**Comment by elynema** [comment] 2023-03-29 17:44
@cjcolvar @Dananji On the surface, just looking at the SME, this is looking good. However, comparing across the SME, the XML editor, and the record itself, I am seeing some puzzling differences.

Example record: https://avalon-dev.dlib.indiana.edu/media_objects/0g354f213

I was testing what would happen with an empty div, so I added an empty heading with no timespans at the end (labeled "Conclusion"), saved in SME, and then closed. When I re-opened the SME, that empty heading had disappeared, which I understood to be expected behavior. However, the empty heading is still showing on the item page. Additionally, the XML editor doesn't show either of the timespans.

SME: ![image.png](https://images.zenhubusercontent.com/62d989a70c79cb5218735cd6/8d185eee-d732-493c-925c-4f1ae22a6caa)

XML editor: ![image.png](https://images.zenhubusercontent.com/62d989a70c79cb5218735cd6/456391f8-eb3a-41e6-8c12-5863f8d051ee)

Item view page: ![image.png](https://images.zenhubusercontent.com/62d989a70c79cb5218735cd6/aeda69ba-4593-4181-b6f5-402c44d7ebae)

**Comment by Dananji** [comment] 2023-03-29 18:20
After making changes to the structure in SME, the page needs to be reloaded to reflect the changes in XML editor. If you reload the page you can see the new timespans in XML editor.

Since IIIF spec specifies that `Range`s should at least have on item, the filter for childless `divs` is only applied at manifest generation step.
And both item page and XML editor displays the structure as it is, while SME uses the manifest which explains difference between structure in these instances.

**Comment by elynema** [comment] 2023-03-31 14:36
We discussed validating structural metadata in the endpoint at time of save, which would allow us to prevent the creation of childless divs in both the SME and XML editor for consistency sake, and would allow us to show a useful error message to users.

However, we are concerned about existing structural metadata that may have childless divs (or headings without timespans). In the current implementation, if that structural metadata is pulled up in the SME and then saved, those childless divs will be lost. If we implement a validation filter across both SME and XML editor, then that data will be lost (or have to be moved somewhere else) in both editors. 

It would be helpful to have a survey of how / if this type of data is being saved into structural metadata.

In the short term, Chris has worked on testing a IIIF with childless range in structures section to determine if it is truly out of compliance with IIIF. It seems to be passing the validator and working in viewers, so if that goes well, the proposal is to revert the work in pull request #5113 and allow childless divs to be created. These should be able to be handled by the SME as the problem was with the IIIF manifest, now the SME?

See #5141 for testing results.

**Closed** 2023-04-05 17:45 UTC
Labels: bug 🐛
