### ISSUE TITLE
Add to Playlist

### ISSUE THREAD

**Issue by joncameron** [avalonmediasystem/avalon#5316] opened 2023-08-16 19:14 UTC
# Description
Add to Playlist functionality as part of the media object view page rework. This will be implemented as Avalon functionality, rather than a Ramp component. We've attempted to re-work multiple add to playlist buttons that currently appear in the interface into a single button that provides all available options. 

# Definition of Done
- [ ] Add to Playlist button shows up only next to the Create Thumbnail button (not in player or in structured metadata display) and opens as an accordion instead of a modal popup
- [ ] Users can add item to an existing playlist (select from drop-down) or create a new playlist
  - [ ] The playlist drop down is the same as in current Avalon (see screenshot below) with the option to create a select an existing playlist or create one
  - [ ] If a user has no playlists, they are prompted to create one (see #5391 for the work of implementing the "add to playlist" modal
- [ ] Default in select playlist drop-down is first playlist (alphabetical order)
- [ ] Select playlist drop-down provides a type-ahead
- [ ] Add to Playlist button provides 4 options to users to add content to playlist
  - [ ] Users can add current track
    - [ ] The currently active track label is set as the default Title
  - [ ] Users can add a custom time scoped item to playlist. Start time for custom time is set to the current playhead position, and end time is end of current track (currently selected segment)
    - [ ]  The currently active track label is set as the default Title
  - [ ] Users can add the current section, with option to create a single playlist item for section, or one for each track (segment). If user adds current section as a single playlist item, should be able to create title / description for playlist item.
  - [ ] Users can add all sections, each as a single playlist item
  - [ ] If 'Current Track" or "Time Selection" are selected, the Title and Description fields display; the "Create playlist items for each track" check box does not display
  - [ ] If 'Current Section" or "All Sections" are selected, the Title and Description fields do not display; the "Create playlist items for each track" check box displays
  - [ ] Current Section and Current Track options display the appropriate label for section or track in parentheses in the form label text

# WIP Mockup
## Current Track
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcG5qIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--1e0fa0022325ae4722ba76db494c23194a6cf171/current_track.png)

## Current Section
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBcHZqIiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--d563a77032190794f56d5e9bc5b23ab962862c16/current_section.png)

# Playlist Drop-down
![Screenshot 2023-09-27 at 2 51 56 PM](https://github.com/avalonmediasystem/avalon/assets/1406618/5eb6ad86-3234-46c9-a289-0ddd6745f62a)

# Whiteboard Mockup
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBc0k4IiwiZXhwIjpudWxsLCJwdXIiOiJibG9iX2lkIn19--cfd28bd26dc057df73226e0c7ce4bb53e0701b36/IMG_4408.jpeg)

**Comment by joncameron** [comment] 2023-09-13 19:35
- Hide "create for each track" checkbox unless the user selects the radio button for the two applicable values, current section and all sections
- Current section/all sections will not require the Title and Description form fields.

**Comment by joncameron** [comment] 2023-09-27 19:20
Other considerations:
- existing concatenation of labels into playlist item labels

**Comment by elynema** [comment] 2023-10-20 16:26
@joncameron When Dananji demoed this today, if the user does not have a playlist, it first tells them to create a playlist and then they have to reload the page before the add to playlist form shows up. However, the drop-down to select a playlist does seem to have a working 'add playlist' component so I'm not sure this workflow is necessary. Need to determine if we want to leave it as is or make a change in this first release.

Also consider: 
Do we want to label the playlist selection drop-down or move it under the header so it is in-line with all the other actions? (I probably favor the latter).
Perhaps we should bold the header text?
We use "current track" and "track/subsection" language in the box - not sure if we should standardize?

**Comment by charumitraravi** [comment] 2023-11-02 18:16
Results if exploratory QA
1. When there are no timelines in a section, Add to playlist button does nothing. (Add to playlist opens the accordian view only if the current part is a timeline, ie, when there is a marker) [Refer the screengrab 1]
[Screengrab 1 ](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMk9hQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--74ecab3621971299d3667f5f70156e47817e3780/Screen%20Recording%202023-11-02%20at%201.50.14%20PM.mov)
Is this expected?

2. Unable to add text in the beginning of the title [Refer screengrab 2 - first half] (Sporadic issue)
3. Editing the title resets when I click on any of the radio buttons again/ edit time selection  [screengrab 3]
[screengrab 3](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMythQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--f457e8a520d5890e0fb6da6a225c9a0e5834e771/Screen%20Recording%202023-11-02%20at%202.12.28%20PM.mov)

4. Once a playlist is added and the success message is received, the user is unable to add playlists again [Refer second half of screengrab 2]
[Screengrab 2](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjJhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--0bb6833f3409b55c9b2d6f3c475edc124573bcd3/Screen%20Recording%202023-11-02%20at%201.50.14%20PM.mov)

5.The "Add to playlist" button is disabled sometimes randomly (I was able to reproduce this issue just by refreshing the page after adding a section to a playlist)
[Private Zenhub Image](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBMjZhQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--c8e9a693746cb17ad2b16c199324f2b8ede33840/Screenshot%202023-11-02%20at%202.05.55%20PM.png)

**Comment by elynema** [comment] 2023-11-03 13:49
When user has the add to playlist form open, and clicks a spot in the media file outside of any timespan, the current track option should be disabled and the current track name text (in parentheses) should be removed, since there is no current track.

**Comment by Dananji** [comment] 2023-11-03 15:03
I tested the results from QA after the bug fixes were merged, and this is what I saw in order they were reported;
1. Not able to reproduce. Not sure whether this got fixed by the bug-fix PR unintentionally.
2. Not able to reproduce.
3. Definitely a bug and need to be fixed, I can create a bug ticket for this.
4. This got fixed by the bug-fix work
5. Add to playlist button is disabled intentionally when switching between sections until the player is fully loaded. @charumitraravi is this similar to what you saw?

**Comment by charumitraravi** [comment] 2023-11-03 16:11
1.This seems fixed now
2.It was a sporadic issue like I mentioned. i will add a comment if I can find a pattern where it can be reproduced.
3.Please let me know if you need me to create a bug for this issue.
4.Verified the fix
5.The button remains disabled even after the player is loaded
[Button disabled issue ](https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBeHVnQVE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--2b9ddb61dea52880e953970fe439b17cddac3350/Screen%20Recording%202023-11-03%20at%2012.03.01%20PM.mov)
Steps to reproduce:
- Open an item, and add a section or a track to a playlist
- Refresh the page
- Play any section with timelines in the item
[Rf: https://avalon-dev.dlib.indiana.edu/media_objects/9k41zd49s]

Is this behavior expected?

@Dananji @elynema

**Closed** 2023-11-07 14:39 UTC
