### ISSUE TITLE
Special characters in item and transcript search

### ISSUE THREAD

**Issue by masaball** [avalonmediasystem/avalon#5971] opened 2024-08-02 17:14 UTC
Follow on from #5967

In 5967 it was found that curly braces were causing an error when included in transcript searches. For 7.8 release we are going to skip the "Found in Transcript" path when there are curly braces in a search query. Moving forward, is this approach sufficient or do we need to find a better solution?

1. Are there other special characters that cause issues with searches? Most special characters are going to be edge cases for searching, so should we worry about them before an error or user complaint crops up?
2. Why are curly braces failing? We are running queries through `RSolr.solr_escape` before they hit the transcript search path. Is the escape character wrong or is there a setting on Solr's end where it is not respecting that the character has been escaped? Could there be some other issue?
3. Are there concerns with the current approach of skipping transcripts when there are curly braces in the query?

No other special characters that we're aware of that aren't working, but it would be good to verify the regex special characters since regex strings will probably make it into search queries.

# Done Looks Like
- [x] Investigation of the current failure path in the search request and how Solr is handling these
- [ ] Can a user just use regex characters in a search query and expect it to be fine?

**Comment by joncameron** [comment] 2024-08-07 18:09
Current behavior is OK as long as users are fine with some of these characters not being included in search. Investigation would still be good so we know exactly what the issue is inside search/Solr.

**Comment by masaball** [comment] 2024-08-13 18:56
Regex special character failures:
```
$: Error: Error parsing fieldname: Expected identifier at pos 21 str='termfreq(mods_tesim,$),structure_tf_0:termfreq(section_label_tesim,$),transcript_tf_0'

^: Error: org.apache.solr.search.SyntaxError: Cannot parse '({!edismax v="\^"}) {!join to=id from=isPartOf_ssim}{!join to=id from=isPartOf_ssim}transcript_tsim:\^': Encountered "<EOF>" at line 1, column 102.
    Was expecting:
    <NUMBER> ...

): Error: Error parsing fieldname: Expected identifier at pos 0 str='),structure_tf_0:termfreq(section_label_tesim,\)),transcript_tf_0'

{: Error: org.apache.solr.search.SyntaxError: Cannot parse 'transcript_tsim:\': Lexical error at line 1, column 18. Encountered: <EOF> (in lexical state 3)
```

Interestingly it is only ')' and '{' that trigger the errors, not parantheses or curly braces in general.

In my digging and experimenting I have been unable to specifically determine why these errors are happening. We are escaping the characters properly on our end, but something is going wrong on the solr end. From doing some test queries in the solr dashboard, I think what may be happening is that Solr is escaping our escape characters. So a query for `\{` is showing in the `q` param of the dashboard as `\\{` which would cause Solr's parser to interpret the back slash as a backslash and the curly bracket as a non-escaped special character.

The errors only trigger when the `({!edismax v=\"#{RSolr.solr_escape(solr_parameters[:q])}\"})` parameter is included in the query with `deftype=lucene`, so it may have to do with how the two parsers are interacting? 

For now, I think we are fine to leave the search logic as it is and we can maybe revisit the approach if we see/hear that users are trying to run searches with the listed special characters.

**Comment by masaball** [comment] 2024-09-04 19:28
#6013 will likely take care of these problematic characters. We have logic in place for allowing the regex search we know is being used in the ATOM feed, everything else being caught by standard error handling may be sufficient for now.

The honeybadger report linked in the other ticket has a `%29` in the search query, which is the url encoding for `)`. Hard to say if that is the specific issue that caused the error or something else in the query, but preventing those errors will likely cover these as well.

**Comment by joncameron** [comment] 2024-09-11 19:26
Closing this for #6013.

**Closed by joncameron** 2024-09-11 19:26 UTC
Labels: investigation 💡
