### ISSUE TITLE
100 item batch ingest failing

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#2922] opened 2018-04-17 17:44 UTC
### Description
Servers: mco-staging, pawpaw

When the user uploads a manifest file containing 100 items, it fails with a title field error and doesn't start the  ingest process. Where as the same file with less number of items ingest successfully.

**Comment by cjcolvar** [comment] 2018-04-18 20:31
@Karthikeya212 are you able to give a link or point me to where the failing batch is?

**Comment by Karthikeya254** [comment] 2018-04-18 21:51
@cjcolvar It fails to start the ingest process itself, this link (https://iu.app.box.com/folder/31130013694) has a zip file with manifest files and assets folder containing the items. Use onr of the 100 item manifest files to check the failure.

**Comment by cjcolvar** [comment] 2019-05-23 16:38
@joncameron @davidschober Is this still an issue that needs investigation or can it be closed (and removed from the Known Issues)?

**Comment by joncameron** [comment] 2019-05-23 17:44
I'll test this and close if possible. Most likely this is now resolved.

**Comment by joncameron** [comment] 2019-05-23 18:18
Couldn't reproduce; the 100-item manifest came through without a problem. Closing and removing from Known Issues.

**Closed by joncameron** 2019-05-23 18:18 UTC
Labels: bug 🐛
