### ISSUE TITLE
[6.0 Specific]:- Search doesn't return any result even though valid keyword is used.

### ISSUE THREAD

**Issue by anirudhpillai16** [avalonmediasystem/avalon#1268] opened 2016-10-13 18:12 UTC
Environment :- https://spruce.dlib.indiana.edu
Devices:- All Devices/Browsers

**Steps to Reproduce**
1. Launch URL on any browser.e.g:- Chrome.
2. Navigate to Browse and make a note of any audio or video title. e.g:-  "I have a dream--" the life of Martin Luther King
3. Search using same title or part of it as keyword.e.g:- Dream or Martin Luther.

Observe search doesn't return any result with valid keyword.

Note:- This issue is not reproducible on 5.1.4.

**Done looks like**
Search should return all files which uses same keyword in title.

Please refer attached screenshots for details:-
![spruce_search](https://cloud.githubusercontent.com/assets/15963595/19361335/5006ce52-9150-11e6-88ba-c2a8dc847818.JPG)
![mallorn_search](https://cloud.githubusercontent.com/assets/15963595/19361340/54cab296-9150-11e6-9635-caaed07a8163.JPG)

**Comment by davidschober** [comment] 2016-10-27 14:23
Possibly a config mismatch. Per @bmquinn couldn't reproduce on Dev Machine.

**Comment by cjcolvar** [comment] 2016-10-27 14:55
My guess is that we're missing a method from our default_processor_chain in the search_builder or our search builder isn't being called and thus we're not getting our parms added to the solr query.  

Example:
Started GET "/catalog?utf8=%E2%9C%93&search_field=all_fields&q=king" for Solr query: post select {"qt"=>"search", "facet.field"=>["avalon_resource_type_ssim", "creator_ssim", "date_sim", "genre_sim", "collection_ssim", "unit_ssim", "language_sim", "workflow_published_sim", "created_by_sim", "read_access_virtual_group_ssim", "date_digitized_sim", "date_ingested_sim"], "facet.query"=>[], "facet.pivot"=>[], "fq"=>["has_model_ssim:\"MediaObject\""], "hl.fl"=>[], "rows"=>10, "q"=>"king", "sort"=>"score desc, title_ssort asc, date_ssi desc"}
Solr fetch (49.1ms)

**Comment by csyversen** [comment] 2016-10-27 19:37
This might be an issue with solr. When I pull up spruce's solr instance in the browser and run this query: `http://spruce.dlib.indiana.edu:8983/solr/avalon/select?fq=has_model_ssim:MediaObject&indent=on&q=dream&wt=json` i get no results. I can pull up the record in solr if I use it's fedora id though: `http://spruce.dlib.indiana.edu:8983/solr/avalon/select?fq=has_model_ssim:MediaObject&indent=on&q=c1/69/30/26/c1693026-4c16-4c2c-b01f-0bf9e88d200f&wt=json` and you can see that it's populated with a bunch of data that all looks correct and should be hit during the previous query. 

However, locally all of this works as expected. I'm sort of stuck here now, could spruce's solr index/app be messed up?

**Comment by bkeese** [comment] 2016-10-27 20:10
The schema is missing completely from the spruce avalon solr core for some reason.

**Comment by bkeese** [comment] 2016-10-27 20:16
This query works. It's the query that the solr ui made and it's a bit different, but I don't know why:
http://spruce.dlib.indiana.edu:8983/solr/avalon/select?indent=on&q={!term%20f=title_tesi}dream&wt=json

**Comment by csyversen** [comment] 2016-10-27 20:40
one thing i just noticed is that i'm running solr 6.2 locally and spruce is running 6.1. It's a longshot, but maybe it's a bug that's fixed in 6.2?

**Comment by carrickr** [comment] 2016-10-27 20:52
@csyversen So we set all our all default fields in catalog_controller, so it makes sense that your search fails because solr has no default fields (check out the schema.xml where we have default search field commented out:

` 
`

So Brian's query working where he sets the field and yours failing without the field makes sense from a pure querying of solr.  It seems like the issue would in our catalog controller where we bring the title field in as a default field.  Title field name may have changed.

**Comment by carrickr** [comment] 2016-10-27 20:55
https://github.com/avalonmediasystem/avalon/blob/develop/app/controllers/catalog_controller.rb#L127

I'm wondering if those add blocks no longer work with out Blacklight upgrade?

**Comment by csyversen** [comment] 2016-10-27 20:56
searching works when i'm running avalon locally though. If it were a blacklight configuration problem wouldn't we be seeing this issue everywhere?

**Comment by carrickr** [comment] 2016-10-27 20:57
I'm down for upgrading to 6.2 and seeing what happens!

**Comment by joncameron** [comment] 2016-10-28 14:46
@carrickr @phuongdh Go for 6.2 and let's see if that does the trick.

**Comment by csyversen** [comment] 2016-11-01 21:03
so @phuongdh upgraded solr to 6.2, but we're still seeing this issue on spruce. I still can't replicate this locally and even new records are being indexed properly on my local dev machine. I'll bring this up in standup tomorrow, but I'm stuck right now

**Comment by cjcolvar** [comment] 2016-11-03 15:44
@phuongdh fixed this by updating the solrconfig.xml for avalon's core on spruce to be in line with what was committed.

**Closed** 2016-11-03 15:44 UTC
Labels: 6.0, bug, sprint 113
