### ISSUE TITLE
Audio player icons going out of alignment in Microsoft Edge

### ISSUE THREAD

**Issue by Karthikeya212** [avalonmediasystem/avalon#1762] opened 2017-03-16 15:42 UTC
### Descriptive summary
Server: spruce.dlib.indiana.edu
Testing: Browser Compatibility
Browser: Microsoft Edge (25.10586.672.0)
Operating System: Windows10
Issue: On hovering over the audio icon in the audio player, the quality and playlist icons are going out of alignment with the player.

### Steps to reproduce the behavior

1. Login to spruce in Edge browser.
2. Open an audio file (can use item "R_Batch" on spruce to check the issue).
![audio player in edge](https://cloud.githubusercontent.com/assets/25850972/24004633/3414b2e8-0a3d-11e7-8d14-df91f0f298f1.PNG)

3. Hover over the audio icon to see the audio adjustment bar. As the bar appers, quality and playlist icons get misaligned with the player.
![audio player hover in edge](https://cloud.githubusercontent.com/assets/25850972/24004703/600cf54a-0a3d-11e7-8240-ffb331d7414d.PNG)

### Related work

Link to related tickets or prior related work here.

**Comment by Karthikeya212** [comment] 2017-03-16 15:47
This issue is present in R5 also

**Comment by mschnaars** [comment] 2017-09-21 16:21
Is this bug for Edge or for Chrome? The title says Edge, but the steps to reproduce say Chrome. I was unable to reproduce this in Edge.

**Comment by Karthikeya212** [comment] 2017-09-21 16:26
I still can reproduce it on this particular Edge Browser version.

![image](https://user-images.githubusercontent.com/25850972/30706969-075758da-9ec8-11e7-8caf-41ca21126a95.png)

**Comment by joncameron** [comment] 2019-05-16 14:02
Wontfix for this very minor browser-specific styling issue.

**Closed by joncameron** 2019-05-16 14:02 UTC
Labels: bug 🐛, wontfix
