### ISSUE TITLE
Thumbnail disappears after moving item

### ISSUE THREAD

**Issue by mcwhitaker** [avalonmediasystem/avalon#1066] opened 2016-08-16 21:26 UTC
In mallorn I moved an item from one collection to another. When I did that, the thumbnail disappeared. I moved it back to the original collection and the thumbnail is still missing. I then tried updating the poster image, which succeeded, but the thumbnail is still missing.

The item I used for this testing is avalon:8527 titled "Free demo video".

- [ ] retest in 6.0 @anirudhpillai16

**Comment by davidschober** [comment] 2016-09-27 20:42
@anirudhpillai16 can you reproduce this?

**Comment by anirudhpillai16** [comment] 2016-09-28 20:05
@davidschober :- unable to verify this issue since it is blocked by 1193 (https://github.com/avalonmediasystem/avalon/issues/1193)

**Comment by mcwhitaker** [comment] 2016-09-28 20:20
@davidschober @anirudhpillai16 Anirudh and David: this issue was found in r5. It can be reproduced in r5. It makes sense that you cannot reproduce it yet in r6 because you cannot even setup the test scenario in r6 since you cannot create the thumbnails there that you will try to see disappear.

**Comment by anirudhpillai16** [comment] 2016-10-12 17:34
Thumbnail no longer disappears on moving item to different collection hence closing this issue.

**Closed** 2016-10-12 17:34 UTC
Labels: bug
