### ISSUE TITLE
Progress doesn't show without reload of page

### ISSUE THREAD

**Issue by davidschober** [avalonmediasystem/avalon#1197] opened 2016-09-29 14:34 UTC
- [ ] look over conversion progress bar. Doesn't seem to be showing accurate results
- [ ] Investigate before HC.

**Comment by joncameron** [comment] 2016-09-29 14:35
![capture](https://cloud.githubusercontent.com/assets/16720883/18890971/693d1e16-84d1-11e6-9a2c-880cd218643c.PNG)

**Comment by joncameron** [comment] 2016-09-29 14:44
Maria's original story:
URL:- spruce.dlib.indiana.edu
Devices:- All Devices/Browsers

Steps to Reproduce

    Access URL in any browser.
    Login with valid credentials.
    Create New item in any collection by uploading any video or audio.

    Wait for Conversion process.

    The conversion scrubber never shows the item being processed and we don't get the sense that the transcoding worked.

Note:- 1. When going to the item via browsing the collection, one sees the item there. However, the player starts from 00:02 instead of 00:00.
2. Issue is not reproducible on mallorn.

Done looks like
Conversion process should show progress to notify user .

Please refer attached screenshot for details:

**Comment by cjcolvar** [comment] 2016-11-03 16:02
Is this still an issue?

**Comment by anirudhpillai16** [comment] 2016-11-03 17:03
This issue is no longer reproducible. Progress is shown to user during conversion hence closing it.

**Closed** 2016-11-03 17:03 UTC
Labels: 6.0, bug, quality assurance
