### ISSUE TITLE
[6.0 Specific]:- Page freezes or becomes unresponsive when user tries to create new collection.

### ISSUE THREAD

**Issue by anirudhpillai16** [avalonmediasystem/avalon#1180] opened 2016-09-26 19:46 UTC
Environment:- spruce.dlib.indiana.edu
Devices:- All Devices/Browsers

**Steps to Reproduce**

1. Launch URL on any browser.
2. Login with valid credentials.
3. Navigate to Manage content.
4. Create Collection.

Observe sometimes page freezes on clicking create collection or after entering details and then accessing create collection.

Note:- 
1. Reproducibility for this issue is 4/5.
2. Issue is not reproducible on mallorn.

**Done looks like**
User should be able to create collection without any error or freeze.

Please refer attached screenshots for details:

**Comment by anirudhpillai16** [comment] 2016-09-26 19:46
![create_collection_issue](https://cloud.githubusercontent.com/assets/15963595/18849308/62aa181e-8400-11e6-9e0e-caf8ca815f61.jpg)
![create_collection_phone](https://cloud.githubusercontent.com/assets/15963595/18849309/64a38e8e-8400-11e6-898c-3bf433aa599c.jpg)

**Comment by cjcolvar** [comment] 2016-09-27 17:37
I wasn't able to reproduce this today.  Could you test this again and see if it is still happening?

**Comment by davidschober** [comment] 2016-09-27 20:30
@anirudhpillai16 can you test again?

**Comment by joncameron** [comment] 2016-09-27 20:34
I tested this and was not able to reproduce. I know it's intermittent, so I'm going to close this and we can reopen if the issue pops up.

**Closed** 2016-09-27 20:34 UTC
Labels: bug
