### ISSUE TITLE
Playlist Items - item link same player start time not updating

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2567] opened 2017-12-14 18:16 UTC
### Description
In the playlist items page, playlist items sidebar, when clicking on an item which is the same media source (same player), the start time is not updating.

Related to #2533

**Comment by bkeese** [comment] 2017-12-14 18:27
FWIW, I'm not seeing this problem locally.

**Comment by adamjarling** [comment] 2017-12-14 18:38
@bkeese Here's a screen cast what I'm seeing locally:  https://screencast.com/t/WAUXA0nNlB

**Comment by bkeese** [comment] 2017-12-14 18:47
You might try again after my latest PR is merged. Travis should be done soon.

**Comment by adamjarling** [comment] 2017-12-14 18:48
I found an area which I think needs to be updated.  I'll put in a PR and tag you and @phuongdh

**Comment by adamjarling** [comment] 2017-12-15 16:38
@bkeese @phuongdh @cjcolvar This got merged yesterday.  Is someone having another look at this, or did I forget to move it into the Needs Review/Done column?

**Comment by bkeese** [comment] 2017-12-15 16:44
Which PR was it?

**Comment by adamjarling** [comment] 2017-12-15 16:46
https://github.com/avalonmediasystem/avalon/pull/2568/

**Comment by cjcolvar** [comment] 2017-12-19 17:16
I'm not able to reproduce.  Closing.

**Closed by cjcolvar** 2017-12-19 17:16 UTC
Labels: 1 | MediaElement Upgrade, 6.3, bug, In Review, quality assurance
