### ISSUE TITLE
Add To Playlist multiples error

### ISSUE THREAD

**Issue by adamjarling** [avalonmediasystem/avalon#2574] opened 2017-12-14 22:47 UTC
### Description
When adding an item to a playlist in the media view page, adding one item creates multiple playlist entries.

This is probably something to do with an event handler not being removed.

### Done Looks Like
- Only one playlist item is added when adding a playlist item from the media object page.  Even if multiple sections with different players have been clicked multiple times prior to adding a playlist item.

![add-item-to-playlist-multiple-error.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/58bd8fcc0f976f2000dddaf2/125516c66e82c728ace21e0d46e9909e6e8b97ac82a4ab4ce94dfc95304a2e603d49ae3e7c91ea38b34736041d1d11ee53444d04bea6d37ef5f22e7a98590ce9876c5d27cf6942aaea831dbf06ba248e1ed3b1bc8c5edcfa7f74b9dfd0126754505a9bf54f34a8934acd59f549e84c53a010376ae4647b.png)

**Comment by joncameron** [comment] 2017-12-19 21:17
Couldn't reproduce, everything looks good—closing.

**Closed by joncameron** 2017-12-19 21:17 UTC
Labels: 1 | MediaElement Upgrade, 6.3, In Review, quality assurance
