### ISSUE TITLE
[BUG] Series not showing up in metadata for item listed under Series filter

### ISSUE THREAD

**Issue by elynema** [avalonmediasystem/avalon#5361] opened 2023-09-11 17:39 UTC
**Describe the bug**
Series metadata is now showing up for title Horses and Men, even though the title is listed when "First series" value is selected under Series facet. This Series filter for "First series" brings up 2 records. The first record is not showing a series value in its metadata. Second record looks like I would expect it. 

**To Reproduce**
Steps to reproduce the behavior, including the results:
1. Go to [search results](https://avalon-dev.dlib.indiana.edu/catalog?f%5Bseries_ssim%5D%5B%5D=First+series&q=&search_field=all_fields) with 'First series' Series facet value selected. 
2. Click on first title ([Horses and Men](https://avalon-dev.dlib.indiana.edu/media_objects/000000000))
3. No series displays in metadata
4. Click on second title ([Test item with series data](https://avalon-dev.dlib.indiana.edu/media_objects/np193917x))
5. Several series display in the metadata

**Expected behavior**
We would expect the Series heading to be listed under the first title's metadata with value "First series".

**Environment (please complete the following information):**
 - Device / platform: Mac laptop
 - OS: Monterey
 - Browser: Chrome
- [ x] avalon-dev
- [ ] avalon-staging
- [ ] mco-staging
- [ ] mco-production
- [ ] demo

**Release:**
7.7

**Additional notes**
Note that this item does have that weird identifier. It shouldn't be related, but I did notice it.

**Comment by joncameron** [comment] 2023-09-13 17:57
I was able to reproduce the original steps, but after I saved the item again it appeared to update the index as expected and I no longer see "Horses and Men" listed under 'First Series'. I created a new object with "First series" as the series title, which saved and appeared in the catalog listing for 'First Series'. Removing this value from the series field in the Resource Description form and saving seemed to kick the index off as expected and I could no longer see the record under a catalog search for 'First Series'.

**Comment by joncameron** [comment] 2023-09-13 19:10
Since it couldn't be reproduced, this is most likely indexing oddness. More testing could be worthwhile before we close.

**Comment by joncameron** [comment] 2023-09-13 19:10
Timeboxed to a 1 for testing/confirmation.

**Comment by masaball** [comment] 2023-10-11 18:14
Still unable to reproduce on Dev or my local instance. Closing.

**Closed by masaball** 2023-10-11 18:14 UTC
Labels: bug 🐛
