### ISSUE TITLE
Reloading a page is not displaying media object in Edge 16

### ISSUE THREAD

**Issue by SumithBaddam** [avalonmediasystem/avalon#3932] opened 2020-01-10 15:34 UTC
**Summary:**
Server: mallorn.dlib.indiana.edu
Testing: Regression
Browsers: Edge 16
Operating System: Windows 10
Issue: Reloading a page is not displaying media object in Edge 16. Works fine in Edge 19(latest).

**Steps to reproduce this behavior:**
1. Open browser instance on Browserstack
2. Login to Avalon system with a valid user credentials.
3. Browse for a video or audio file and click on the play icon. It plays.
4. Reload the same page, the media file won't get displayed.

**Error:**
The media file is not displayed once a page is reloaded.
![image](https://user-images.githubusercontent.com/6374927/72164969-ad117400-3394-11ea-99d3-7fc6e1e170bf.png)

**Comment by joncameron** [comment] 2020-02-06 15:32
Most likely the initialization to display the media player isn't getting fired correctly. There have been issues with the JS initializing the player hits an exception. Our JavaScript probably isn't resilient enough to handle this.

**Comment by cjcolvar** [comment] 2020-03-10 16:11
In my browserstack testing, the player is appearing on reload but not streaming because of #3729.  But I also wasn't able to reproduce the original failing behavior on mallorn.  This PR doesn't hurt anything so I'm in favor of keeping it, closing the issue, and testing again on a server where browserstack can stream when we're able to.

**Closed** 2020-03-16 15:32 UTC
Labels: bug 🐛
